sudo: required
language: python
python: 2.7
services:
  - docker
env:
  - TOX_ENV=py27
git:
  submodules: false

before_install:
  - export PLANEMO_TRAVIS_USER=planemo
  - export PLANEMO_UID=1450
  - export PLANEMO_GID=1450
  - export PLANEMO_HOME=/home/planemo

  - sudo apt-get update -qq
  - sudo apt-get install docker-engine --no-install-recommends -y -o Dpkg::Options::="--force-confmiss" -o Dpkg::Options::="--force-confdef" -o Dpkg::Options::="--force-confnew"
  - docker --version
  - docker info

  - git submodule update --init --recursive
  - sudo groupadd -r $PLANEMO_TRAVIS_USER -g $PLANEMO_GID
  - sudo useradd -u $PLANEMO_UID -r -g $PLANEMO_TRAVIS_USER -d $PLANEMO_HOME -p travis_testing -c "Planemo user" $PLANEMO_TRAVIS_USER
  - sudo mkdir $PLANEMO_HOME
  - sudo chown -R $PLANEMO_TRAVIS_USER:$PLANEMO_TRAVIS_USER $PLANEMO_HOME

install:
  - pip install ansible

script:
  # Check the role/playbook's syntax.
  - ansible-playbook -i "localhost," provision.yml --syntax-check
  # Build the docker containers
  - docker build -t planemo/interactive .
  - cd server
  - docker build -t planemo/server .
  - |
      docker run -d -p 8080:80 \
        --name planemo \
        -e GALAXY_CONFIG_ALLOW_USER_DATASET_PURGE=True \
        -e GALAXY_CONFIG_ALLOW_LIBRARY_PATH_PASTE=True \
        -e GALAXY_CONFIG_ENABLE_USER_DELETION=True \
        -e GALAXY_CONFIG_ENABLE_BETA_WORKFLOW_MODULES=True \
        planemo/server
  - sleep 180
  - docker ps
  - docker logs planemo
  - docker exec planemo bash /usr/bin/check-planemo-machine.sh
  - export BIOBLEND_GALAXY_API_KEY=HSNiugRFvgT574F43jZ7N9F3
  - export BIOBLEND_GALAXY_URL=http://localhost:8080
  - curl -v --fail $BIOBLEND_GALAXY_URL/api/version
