sudo: required
language: python
python: 2.7
services:
  - docker
env:
  matrix:
    - INCLUDE_X=false
    - INCLUDE_X=true

install:
  - pip install ansible

script:
  # Check the role/playbook's syntax.
  - ansible-playbook -i "localhost," provision.yml --syntax-check
  - bash ci_test.sh
